export const expenses = [
  {
    date: "2024-04-01",
    description: "Maintenance Supplies",
    category: "Supplies",
    department: "Maintenance",
    payment: "Credit Card",
    amount: 1234.56,
    status: "Approved",
  },
  {
    date: "2024-04-02",
    description: "Kitchen Equipment",
    category: "Equipment",
    department: "Kitchen",
    payment: "Bank Transfer",
    amount: 2845.0,
    status: "Pending",
  },
  {
    date: "2024-04-03",
    description: "Cleaning Services",
    category: "Services",
    department: "Housekeeping",
    payment: "Credit Card",
    amount: 1500.0,
    status: "Approved",
  },
  {
    date: "2024-04-04",
    description: "Office Supplies",
    category: "Supplies",
    department: "Administration",
    payment: "Cash",
    amount: 456.78,
    status: "Approved",
  },
  {
    date: "2024-04-05",
    description: "Staff Training",
    category: "Training",
    department: "HR",
    payment: "Bank Transfer",
    amount: 2000.0,
    status: "Rejected",
  },
  {
    date: "2024-04-06",
    description: "Food Supplies",
    category: "Supplies",
    department: "Restaurant",
    payment: "Credit Card",
    amount: 3456.89,
    status: "Approved",
  },
  {
    date: "2024-04-07",
    description: "Furniture Repair",
    category: "Maintenance",
    department: "Rooms",
    payment: "Cash",
    amount: 890.0,
    status: "Pending",
  },
  {
    date: "2024-04-08",
    description: "Marketing Campaign",
    category: "Marketing",
    department: "Sales",
    payment: "Bank Transfer",
    amount: 5000.0,
    status: "Approved",
  },
  {
    date: "2024-04-09",
    description: "Utility Bills",
    category: "Utilities",
    department: "Facilities",
    payment: "Bank Transfer",
    amount: 4567.89,
    status: "Approved",
  },
  {
    date: "2024-04-10",
    description: "Pool Maintenance",
    category: "Maintenance",
    department: "Facilities",
    payment: "Credit Card",
    amount: 789.45,
    status: "Pending",
  },
  {
    date: "2024-04-11",
    description: "Lobby Renovation",
    category: "Renovation",
    department: "Facilities",
    payment: "Bank Transfer",
    amount: 12500.0,
    status: "Approved",
  },
  {
    date: "2024-04-12",
    description: "Staff Uniforms",
    category: "Supplies",
    department: "HR",
    payment: "Credit Card",
    amount: 3200.0,
    status: "Approved",
  },
  {
    date: "2024-04-13",
    description: "IT Equipment",
    category: "Equipment",
    department: "IT",
    payment: "Bank Transfer",
    amount: 5678.9,
    status: "Pending",
  },
  {
    date: "2024-04-14",
    description: "Plumbing Repairs",
    category: "Maintenance",
    department: "Maintenance",
    payment: "Cash",
    amount: 750.0,
    status: "Approved",
  },
  {
    date: "2024-04-15",
    description: "Guest Amenities",
    category: "Supplies",
    department: "Rooms",
    payment: "Credit Card",
    amount: 1890.45,
    status: "Approved",
  },
  {
    date: "2024-04-16",
    description: "Security System Upgrade",
    category: "Equipment",
    department: "Security",
    payment: "Bank Transfer",
    amount: 8900.0,
    status: "Pending",
  },
  {
    date: "2024-04-17",
    description: "Landscaping Services",
    category: "Services",
    department: "Facilities",
    payment: "Credit Card",
    amount: 2345.67,
    status: "Approved",
  },
  {
    date: "2024-04-18",
    description: "Restaurant Supplies",
    category: "Supplies",
    department: "Restaurant",
    payment: "Cash",
    amount: 1234.56,
    status: "Approved",
  },
  {
    date: "2024-04-19",
    description: "Staff Bonuses",
    category: "Compensation",
    department: "HR",
    payment: "Bank Transfer",
    amount: 10000.0,
    status: "Approved",
  },
  {
    date: "2024-04-20",
    description: "Elevator Maintenance",
    category: "Maintenance",
    department: "Facilities",
    payment: "Credit Card",
    amount: 3500.0,
    status: "Pending",
  },
  {
    date: "2024-04-21",
    description: "Advertising Campaign",
    category: "Marketing",
    department: "Sales",
    payment: "Bank Transfer",
    amount: 7500.0,
    status: "Approved",
  },
  {
    date: "2024-04-22",
    description: "Bathroom Fixtures",
    category: "Supplies",
    department: "Maintenance",
    payment: "Credit Card",
    amount: 2345.67,
    status: "Rejected",
  },
  {
    date: "2024-04-23",
    description: "Conference Room Equipment",
    category: "Equipment",
    department: "Events",
    payment: "Bank Transfer",
    amount: 4567.89,
    status: "Approved",
  },
  {
    date: "2024-04-24",
    description: "Pest Control",
    category: "Services",
    department: "Facilities",
    payment: "Cash",
    amount: 450.0,
    status: "Approved",
  },
  {
    date: "2024-04-25",
    description: "Laundry Equipment",
    category: "Equipment",
    department: "Housekeeping",
    payment: "Bank Transfer",
    amount: 6789.0,
    status: "Pending",
  },
  {
    date: "2024-03-28",
    description: "Spa Equipment",
    category: "Equipment",
    department: "Spa",
    payment: "Credit Card",
    amount: 9876.54,
    status: "Approved",
  },
  {
    date: "2024-03-25",
    description: "Gym Maintenance",
    category: "Maintenance",
    department: "Fitness",
    payment: "Bank Transfer",
    amount: 1200.0,
    status: "Approved",
  },
  {
    date: "2024-03-22",
    description: "Wine Inventory",
    category: "Supplies",
    department: "Restaurant",
    payment: "Credit Card",
    amount: 5432.1,
    status: "Approved",
  },
  {
    date: "2024-03-20",
    description: "Shuttle Service",
    category: "Transportation",
    department: "Guest Services",
    payment: "Bank Transfer",
    amount: 3000.0,
    status: "Pending",
  },
  {
    date: "2024-03-18",
    description: "Bedding and Linens",
    category: "Supplies",
    department: "Housekeeping",
    payment: "Credit Card",
    amount: 4321.0,
    status: "Approved",
  },
  {
    date: "2024-03-15",
    description: "Software Licenses",
    category: "Software",
    department: "IT",
    payment: "Bank Transfer",
    amount: 2500.0,
    status: "Approved",
  },
  {
    date: "2024-03-12",
    description: "Staff Meals",
    category: "Food",
    department: "HR",
    payment: "Cash",
    amount: 1200.0,
    status: "Approved",
  },
  {
    date: "2024-03-10",
    description: "Electrical Repairs",
    category: "Maintenance",
    department: "Facilities",
    payment: "Credit Card",
    amount: 1875.5,
    status: "Pending",
  },
  {
    date: "2024-03-08",
    description: "Artwork for Lobby",
    category: "Decor",
    department: "Design",
    payment: "Bank Transfer",
    amount: 7500.0,
    status: "Approved",
  },
  {
    date: "2024-03-05",
    description: "Parking Lot Resurfacing",
    category: "Renovation",
    department: "Facilities",
    payment: "Bank Transfer",
    amount: 15000.0,
    status: "Pending",
  },
  {
    date: "2024-03-02",
    description: "Concierge Training",
    category: "Training",
    department: "Guest Services",
    payment: "Credit Card",
    amount: 1500.0,
    status: "Approved",
  },
  {
    date: "2024-02-28",
    description: "Accounting Services",
    category: "Services",
    department: "Finance",
    payment: "Bank Transfer",
    amount: 3500.0,
    status: "Approved",
  },
  {
    date: "2024-02-25",
    description: "Legal Consultation",
    category: "Services",
    department: "Legal",
    payment: "Bank Transfer",
    amount: 4000.0,
    status: "Approved",
  },
  {
    date: "2024-02-22",
    description: "Bathroom Amenities",
    category: "Supplies",
    department: "Rooms",
    payment: "Credit Card",
    amount: 2345.67,
    status: "Approved",
  },
  {
    date: "2024-02-20",
    description: "Fire Safety Inspection",
    category: "Services",
    department: "Security",
    payment: "Bank Transfer",
    amount: 1200.0,
    status: "Approved",
  },
]

